/**
 * MCP analyze 返回中的设计稿还原工作流说明（对标 PY summary_text STEP 1~5）。
 * 仅用于 Agent 行为指引，不参与 @lanhu/core 数据管道。
 */
export function buildDesignWorkflowGuide(): string {
  return [
    "🚨 设计稿代码还原指引（推荐流程）",
    "以下 HTML+CSS 是从设计稿生成的【结构化规格书】，用于辅助理解布局意图与精确参数。",
    "⚠️ 核心原则: 以 Sketch 标注理解结构，以 CSS 代码作为数值参考，允许按需重构布局。",
    "",
    "STEP 1 - 探测用户项目环境：",
    "  读取项目配置文件（package.json / tsconfig.json / pubspec.yaml 等）",
    "  识别框架: React/Vue/Angular/Svelte/Flutter/SwiftUI/Compose/纯HTML",
    "  识别样式方案: Tailwind / CSS Modules / SCSS / Styled Components 等",
    "  识别项目目录结构和命名规范",
    "",
    "STEP 2 - 下载图片资源到本地（必须在生成代码前完成）：",
    "  下方 HTML 代码中的图片已替换为本地路径（./assets/slices/xxx.png）",
    "  必须按下方「图片资源下载映射」下载所有图片到项目本地 assets 目录：",
    '    macOS/Linux → curl -o <path> "<url>"',
    '    Windows → PowerShell Invoke-WebRequest -Uri "<url>" -OutFile <path>',
    '  如需更多切图，调用 lanhu_design(url, mode="slices", design_names=<画板名>)',
    "",
    "STEP 3 - 生成框架适配代码（标注优先，允许重构）：",
    "  参考下方 HTML+CSS 提取颜色、字号、间距、圆角等精确数值。",
    "  结合「图层结构」与「CSS 标注」理解设计意图（如列表、容器、对齐方式）。",
    "  ⚠️ 建议根据项目规范（如使用 Tailwind 类名或 Flex/Grid 布局）对生成的代码进行重构，不要机械复制绝对定位。",
    "  按目标框架生成组件代码：",
    "    React/Next.js  → JSX + CSS Modules / Tailwind",
    "    Vue/Nuxt       → .vue SFC + <style scoped>",
    "    Flutter        → Widget + EdgeInsets/BoxDecoration",
    "    SwiftUI        → View + ViewModifier",
    "    Android Compose → @Composable + Modifier",
    "",
    "STEP 4 - 校验与还原度核查：",
    "  对照「Design Tokens」和「Sketch 完整标注」补充 CSS 未能表达的属性（如复杂渐变、阴影）。",
    "  核查关键视觉元素是否完整，确保图片资源路径正确。",
    "  确保最终代码中不残留任何蓝湖 CDN 远程 URL。",
    "",
    "📐 common.css 工具类含义（用于理解布局意图）：",
    "  flex-col = Column 方向布局    flex-row = Row 方向布局",
    "  justify-between/center/start/end/around/evenly = 主轴对齐",
    "  align-start/center/end = 交叉轴对齐",
  ].join("\n");
}
